
[slime]
	#Slime Blobs Enabled
	enabled = true

[charge]
	#Charge Particle Enabled
	enabled = true

[waterCircle]
	#Water Circles Enabled
	enabled = false
	#Water Circles Colored
	colored = true
	#Water Circles Density
	#Range: 0 ~ 64
	density = 16

