
["Server config for the Weaponized Baseball Mod"]
	#Turn on lite mode which disables slow collisions and throwable on throwable collisions.
	"Lite mode" = false
	#How many ticks a throwable can be idle before despawning. Default value is 1200 (1 min).
	"Throwable Idle Time" = 200
	#Disable overriding the vanilla throwables behaviour to make them hittable with bats.
	"Override Vanilla Throwables" = true
	#Enable throwables dropping themselves after the idle time is over.
	"Throwables drop selves" = true
	#Let the super slimeball's bounciness be bound by the laws of physics.
	"Reduce super slimeball bounciness" = false
	#How many ticks in between consecutive throws. Default value is 12
	"Throwing cooldown" = 12

