
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 858803
	#The name of the modpack
	modpackName = "Raspberry Flavoured"
	#The version of the modpack
	modpackVersion = "3.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

