
["custom text"]
	#Insert the custom title screen text you want here (supports multiple lines)
	text = ["Raspberry Flavoured 2.0.0 Beta 2"]

[versions]
	#Show which version of Minecraft the client is currently running.
	showMcVersion = false
	#Show which version of Minecraft Coder Pack (MCP) the client is running.
	showMcpVersion = false
	#Show which version of Minecraft Forge the client is running.
	showForgeVersion = false
	#Show how many mods are loaded.
	showModsLoaded = false

