
["Config for Enchantment Transfer!"]
	#Here you can set a fixed value for any enchantment transfer from item to book. Default is 1000 which disables the fixed value.
	"Fixed Experience Cost" = 1000
	#Here you can set a factor to multiply any enchantment transfer XP cost by. This will be overwritten if a fixed value other than 1000 is defined. Default is 1.0.
	"Experience Cost Factor" = 5.0
	#Here you can set an enchantment limit to only transfer X amount of enchantments from an item. Default is 1000 which disables the limit.
	"Enchantment Limit" = 3
	#Should the anvil give you back the item you disenchanted? Change this value to 0 to block the original item from being returned. Default is 1.
	"Should Return" = 0

