
["Mob Caps"]
	#Mob cap for monsters. Controls the maximum number of zombies, creepers, etc. Default: 70
	monster = 70
	#Mob cap for creatures. Controls the maximum number of miscellaneous creatures. Default: 10
	creature = 20
	#Mob cap for ambient creatures. Controls the maximum number of bats. Default: 15
	ambient = 15
	#Mob cap for water creatures. Controls the maximum number of squid, dolphins, etc. Default: 5
	water_creature = 7
	#Mob cap for ambient water creatures. Controls the maximum number of fish. Default: 20
	water_ambient = 20
	#Mob cap for underground water creatures. Controls the maximum number of glowsquid. Default: 5
	underground_water_creature = 4
	#Mob cap for axolotls. Controls the maximum number of axolotls. Default: 5
	axolotl = 7

