#Show effect colors in tooltip
effect_color = false
#Draw a black box behind effect icons
effect_box = true
#A list of effects that should not be registered nor shown in JEI
hidden_effects = ["minecraft:hero_of_the_village", "cofh_core:supercharge", "cofh_core:clarity", "ecologics:slippery", "create_confectionery:rest", "create_confectionery:stimulation", "better_beacons:phantom_bane", "better_beacons:patrol_nullifier", "createaddition:shocking", "additional_enchantments:plague", "additional_enchantments:wither", "clash:rampaging", "clash:retaliation", "clash:staggered", "farmersdelight:nourishment"]
#Show ingredients list along with an effect description
ingredients_list = false
#Renders individual slots instead of a big one. Only works for REI
render_slots = false
#Removes vanilla tooltips rendered when an effect renders small (square box)
replace_vanilla_tooltips = true

